Et_Vest-main/ET_Vest/ET_Vest/Controllers/PrintedEditionController.cs
using ET_Vest.Data;
using ET_Vest.Data.ViewModels;
using ET_Vest.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Scaffolding.Shared;
using Microsoft.EntityFrameworkCore;

namespace ET_Vest.Controllers
{
    public class PrintedEditionController : Controller
    {
        private readonly ApplicationDbContext context;

        public PrintedEditionController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            var printedEdition = context.PrintedEditions
            .Include(m => m.PrintEditionProviders)
            .Include(m => m.Requests)
            .ToList();

            return View(printedEdition);
        }

        //Add PrintedEdition
         [Authorize(Roles = "Owner")]
        public IActionResult Add()
        {
            ViewBag.Providers = context.PrintedEditionProviders.Include
                (pp => pp.Provider).ToList();
            ViewBag.Requests = context.Requests.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Add(PrintedEdition printedEdition)
        {
            context.PrintedEditions.Add(printedEdition);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        //Update Printed Editions
         [Authorize(Roles = "Owner")]
        public IActionResult Edit(int id)
        {
            var printedEdition = context.PrintedEditions.Find(id);

            if (printedEdition == null)
            {
                return NotFound();
            }

            var printedEditionProvider = context.PrintedEditionProviders
                    .Include(pe => pe.Provider)
                    .FirstOrDefault(pe => pe.PrintedEditionId == id);

            var viewModel = new PrintedEditionProviderViewModel
            {
                PrintedEdition = printedEdition,
                PrintedEditionProvider = printedEditionProvider
            };
            ViewBag.Providers = new SelectList(context.Providers, "ProviderId", "Name");
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(PrintedEditionProviderViewModel viewModel)
        {
            //update edition details
            context.PrintedEditions.Update(viewModel.PrintedEdition);
            //update printed edition provider details
         //   context.Entry(viewModel.PrintedEditionProvider).State = EntityState.Modified;
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Roles = "Owner")]
        public IActionResult Delete(int id)
        {
            var printedEditions = context.PrintedEditions.Find(id);

            if (printedEditions == null)
            {
                return NotFound();
            }

            context.PrintedEditions.Remove(printedEditions);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Et_Vest-main/ET_Vest/ET_Vest/Controllers/ProviderController.cs
using ET_Vest.Data;
using ET_Vest.Data.ViewModels;
using ET_Vest.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Drawing.Drawing2D;

namespace ET_Vest.Controllers
{
    public class ProviderController : Controller
    {
        private readonly ApplicationDbContext context;

        public ProviderController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            var provider = context.Providers
            .Include(p => p.PrintEditionProviders)
            .ThenInclude(p => p.PrintedEdition)
            .ToList();

            return View(provider);
        }

        //Add Provider
        [Authorize(Roles = "Owner")]

        public IActionResult Add()
        {
            ViewBag.PrintedEditions = context.PrintedEditionProviders.Include
                (ma => ma.PrintedEdition).ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Add(Provider provider)
        {
            context.Providers.Add(provider);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        //Update Provider
        [Authorize(Roles = "Owner")]

        public IActionResult Edit(int id)
        {
            var provider = context.Providers.Find(id);

            if (provider == null)
            {
                return NotFound();
            }

            var printedEditionProvider = context.PrintedEditionProviders
          .Include(pe => pe.PrintedEdition)
          .FirstOrDefault(pe => pe.ProviderId == id);

            var viewModel = new PrintedEditionProviderViewModel
            {
                Provider = provider,
                PrintedEditionProvider = printedEditionProvider
            };
            ViewBag.PrintedEditions = new SelectList(context.PrintedEditions, "PrintedEditionId", "Title");
            return View(viewModel);
        }
        [HttpPost]
        public IActionResult Edit(PrintedEditionProviderViewModel viewModel)
        {
            //update provider details
            context.Providers.Update(viewModel.Provider);
            //update printed edition provider details
          //  context.Entry(viewModel.PrintedEditionProvider).State = EntityState.Modified;
            context.SaveChanges();
            return RedirectToAction("Index");

        }

        [HttpPost]
        [Authorize(Roles = "Owner")]
        public IActionResult Delete(int id)
        {
            var provider = context.Providers.Find(id);

            if (provider == null)
            {
                return NotFound();
            }

            context.Providers.Remove(provider);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Et_Vest-main/ET_Vest/ET_Vest/Controllers/RequestController.cs
using ET_Vest.Data;
using ET_Vest.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Net.Sockets;

namespace ET_Vest.Controllers
{
    public class RequestController : Controller
    {
        private readonly ApplicationDbContext context;

        public RequestController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            var requests = context.Requests
           .Include(t => t.TradeObject)
           .Include(t => t.PrintedEdition)
           .Include(t => t.Provider)
           .ToList();

            return View(requests);
        }
        [Authorize(Roles = "Owner")]

        public IActionResult Add()
        {
            ViewBag.TradeObjects = context.TradeObjects.ToList();
            ViewBag.PrintedEditions = context.PrintedEditions.ToList();
            ViewBag.Providers = context.Providers.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Add(Request request)
        {
            request.Status = "Изчакваща";
            context.Requests.Add(request);
            context.SaveChanges();
            return RedirectToAction("Index");

        }
        [Authorize(Roles = "Owner")]
        public IActionResult Edit(int id)
        {
            var request = context.Requests
                .Include(m => m.TradeObject)
                .Include(m => m.PrintedEdition)
                .Include(m => m.Provider)
                .FirstOrDefault(m => m.Id == id);
            if (request == null)
            {
                return NotFound();
            }

            ViewBag.TradeObjects = context.TradeObjects.ToList();
            ViewBag.PrintedEditions = context.PrintedEditions.ToList();
            ViewBag.Providers = context.Providers.ToList();

            return View(request);
        }

        [HttpPost]
        public IActionResult Edit(Request request)
        {

            context.Requests.Update(request);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Owner")]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var request = context.Requests.Find(id);

            if (request == null)
            {
                return NotFound();
            }

            context.Requests.Remove(request);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Employee")]
        [HttpPost]
        public IActionResult SentToOwner(int id)
        {
            var request = context.Requests.Find(id);

            if (request == null)
            {
                return NotFound();
            }

            request.Status = "Изпратена към собственик"; // Маркиране на съобщението като прочетено

            context.SaveChanges();

            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Owner")]
        [HttpPost]
        public IActionResult SentToProvider(int id)
        {
            var request = context.Requests.Find(id);

            if (request == null)
            {
                return NotFound();
            }

            request.Status = "Изпратена към доставчик"; // Маркиране на съобщението като прочетено

            context.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Employee")]
        [HttpPost]
        public IActionResult DoneRequest(int id)
        {
            var request = context.Requests.Find(id);

            if (request == null)
            {
                return NotFound();
            }

            request.Status = "Изпълнена"; // Маркиране на съобщението като прочетено

            context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

Et_Vest-main/ET_Vest/ET_Vest/Controllers/TradeObjectController.cs
using ET_Vest.Data;
using ET_Vest.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ET_Vest.Controllers
{
    public class TradeObjectController : Controller
    {
        private readonly ApplicationDbContext context;

        public TradeObjectController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            var tradeObject = context.TradeObjects
           .Include(r => r.Requests)
           .ToList();

            return View(tradeObject);
        }

        ////Add TradeObject
        [Authorize(Roles = "Owner")]
        public IActionResult Add()
        {
            ViewBag.Requests = context.Requests.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Add(TradeObject tradeObject)
        {
            context.TradeObjects.Add(tradeObject);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        ////Update TradeObject
        [Authorize(Roles = "Owner")]
        public IActionResult Edit(int id)
        {
            var tradeObject = context.TradeObjects
                .Include(m => m.Requests)
                .FirstOrDefault(m => m.Id == id);
            if (tradeObject == null)
            {
                return NotFound();
            }

            ViewBag.Requests = context.Requests.ToList();

            return View(tradeObject);
        }

        [HttpPost]
        public IActionResult Edit(TradeObject tradeObject)
        {
          //  if (ModelState.IsValid)
           // {

                context.TradeObjects.Update(tradeObject);
                context.SaveChanges();
                return RedirectToAction("Index");
         //   }
         //   return View(tradeObject);
        }

        [HttpPost]
        [Authorize(Roles = "Owner")]
        public IActionResult Delete(int id)
        {
            var tradeObject = context.TradeObjects.Find(id);

            if (tradeObject == null)
            {
                return NotFound();
            }

            context.TradeObjects.Remove(tradeObject);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Et_Vest-main/ET_Vest/ET_Vest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ET_Vest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ET_Vest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ET_Vest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PrintedEdition" asp-action="Index">PrintedEditions</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Provider" asp-action="Index">Providers</a>
                            </li>
                            @*   @if (User.IsInRole("Admin")) *@
                            @*  { *@
                            @*     <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="PrintedEditionProvider" asp-action="Index">PrintedEdition-Provider</a>
                        </li>*@
                            @if (User.IsInRole("Owner"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="Identity"
                                       asp-page="/Account/Register">Register</a>
                                </li>
                            }
                            @*   } *@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="Index">Requests</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="TradeObject" asp-action="Index">TradeObjects</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ET_Vest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>