Et_Vest-main/ET_Vest/ET_Vest/Models/PrintedEditionProvider.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ET_Vest.Models
{
    public class PrintedEditionProvider
    {
        [Key]
            public int PrintedEditionId { get; set; }
            public PrintedEdition PrintedEdition { get; set; }

            public int ProviderId { get; set; }
            public Provider Provider { get; set; }
        }

}

Et_Vest-main/ET_Vest/ET_Vest/Controllers/PrintedEditionProviderController.cs
using ET_Vest.Data;
using ET_Vest.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ET_Vest.Controllers
{
    [Authorize(Roles = "Owner")]
    public class PrintedEditionProviderController : Controller
    {
        private readonly ApplicationDbContext context;

        public PrintedEditionProviderController(ApplicationDbContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            var printedEditionProvider = context.PrintedEditionProviders
            .Include(m => m.PrintedEdition)
            .Include(m => m.Provider)
            .ToList();

            return View(printedEditionProvider);
        }

        //Add PrintedEditionProvider
        public IActionResult Add()
        {
            ViewBag.PrintedEditions = context.PrintedEditions.ToList();
            ViewBag.Providers = context.Providers.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Add(PrintedEditionProvider printedEditionProvider)
        {
            context.PrintedEditionProviders.Add(printedEditionProvider);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Et_Vest-main/ET_Vest/ET_Vest/Views/PrintedEditionProvider/Add.cshtml
@model ET_Vest.Models.PrintedEditionProvider
@{
    ViewData["Title"] = "Create";
}

<h2>Create PrintedEdition-Provider Relation</h2>
<form method="post" asp-action="Add" asp-controller="PrinredEditionProvider">
    <div class="form-group">
        <label asp-for="PrintedEdition"></label>
        <select asp-for="PrintedEditionId" asp-items="@(new SelectList(ViewBag.PrintedEditions, "PrintedEditionId", "Title"))" class="form-control">
            <option value="">Select a printEdition</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Provider"></label>
        <select asp-for="ProviderId" asp-items="@(new SelectList(ViewBag.Providers, "ProviderId", "Name"))" class="form-control">
            <option value="">Select a provider</option>
        </select>
    </div>

    <button type="submit" class="btn btn-primary" asp-controller="PrintedEditionProvider">Create</button>
</form>

Et_Vest-main/ET_Vest/ET_Vest/Views/PrintedEditionProvider/Edit.cshtml
@using ET_Vest.Models.Enums
@model ET_Vest.Models.PrintedEdition

<h2>Edit PrintedEdition</h2>
<form asp-controller="PrintedEditionProvider" asp-action="Edit" method="post">
    <div class="form-control">
        <label asp-for="Title" class="form-label"></label>
        <input asp-for="Title" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Cathegory"></label>
        <select asp-for="Cathegory" asp-items="Html.GetEnumSelectList<Cathegory>()" class="form-control">
            <option value="">Select a category</option>
        </select>
    </div>  
    <div class="form-group">
        <label asp-for="Periodicity"></label>
        <select asp-for="Periodicity" asp-items="Html.GetEnumSelectList<Periodicity>()" class="form-control">
            <option value="">Select a periodicity</option>
        </select>
        <div class="form-group">
            <label asp-for="DeliveredUnitPrice" class="form-label"></label>
            <input asp-for="DeliveredUnitPrice" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="SalePrice" class="form-label"></label>
            <input asp-for="SalePrice" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <label asp-for="PrintEditionProviders"></label>
        <select asp-for="PrintEditionProviders"
                asp-items="@(new SelectList(ViewBag.Providers,"Name"))"
                class="form-control"></select>
    </div>

    <div class="form-group">
        <label asp-for="Requests"></label>
        <input asp-for="Requests" asp-items="@(new SelectList(ViewBag.Requests,"Id"))"
               class="form-control" />
    </div>
    <input asp-for="@Model.PrintedEditionId" class="d-none" value="@Model.PrintedEditionId" />
    <a type="submit" value="Update" class="btn btn-primary" asp-action="Edit" />
</form>

Et_Vest-main/ET_Vest/ET_Vest/Views/PrintedEditionProvider/Index.cshtml
@model IEnumerable<ET_Vest.Models.PrintedEditionProvider>

<h2>PrintEditions List</h2>
<table class="table">
    <thead>
        <tr>
            <th>PrintedEdition Id</th>
            <th>PrintedEdition</th>
            <th>Provider Id</th>
            <th>Provider</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var printedEditionProvider in Model)
        {
            <tr>
                <td>@printedEditionProvider.PrintedEditionId</td>
                <td>@printedEditionProvider.PrintedEdition.Title</td>
                <td>@printedEditionProvider.ProviderId</td>
                <td>@printedEditionProvider.Provider.Name</td>
            </tr>
        }
    </tbody>
</table>
@* @if (User.IsInRole("Admin"))
{ *@
    <a asp-action="Add" asp-controller="PrintedEditionProvider" class="btn btn-success">Add New PrintedEdition-Provider Relations</a>
@* } *@